const data = {
  products: [
    {
      _id: "1",
      name: "Product1",
      category: "Category1",
      image: "/images/p1.png",
      price: 20,
      brand: "brand",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Product2",
      category: "Category2",
      image: "/images/p2.png",
      price: 250,
      brand: "brand",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Product3",
      category: "Category1",
      image: "/images/p3.png",
      price: 220,
      brand: "brand",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Product4",
      category: "Category2",
      image: "/images/p4.png",
      price: 720,
      brand: "brand",
      rating: 4.5,
      numReviews: 50,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Product5",
      category: "Category5",
      image: "/images/p5.png",
      price: 13,
      brand: "brand",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Product6",
      category: "Category6",
      image: "/images/p6.png",
      price: 7,
      brand: "brand",
      rating: 4.5,
      numReviews: 16,
      description: "high quality product",
    },
  ],
};

export default data;
